# Model settings
embedding_dim: 32
mlp_layers: [64, 32, 16, 8]  # MLP architecture
use_gmf: true  # Set false to disable GMF branch
use_mlp: true  # Set false to disable MLP branch
activation_function: "relu"  # Options: "relu", "leaky_relu", "sigmoid", "tanh"

# Training settings
num_epochs: 20
batch_size: 256
learning_rate: 0.001
weight_decay: 0.01
early_stopping_patience: 10

# Dataset settings
num_negatives: 4  # Number of negative samples per positive interaction
train_split: 0.7
val_split: 0.15
test_split: 0.15

# Other
random_seed: 42
